### ISSUE TITLE
Support https url

### ISSUE THREAD

**Issue by megastef** [rchicoli/docker-log-elasticsearch#27]
Please use the following questions as a guideline for an easier understanding of the issue without further inquiry. Thank you.

### Docker version
17.12
### Elasticsearch version
6
### Operation System architecture
Mac OS X
### Expected behavior
Accept HTTPS URL, start container
### Actual behavior
Rejecting HTTPS URL, and container does not start
### Steps to reproduce the behavior

```
docker run --rm  -ti \
>     --log-driver elasticsearch \
>     --log-opt elasticsearch-url=https://logsene-receiver.sematext.com \
>     --log-opt elasticsearch-index=indexName \
>     --log-opt elasticsearch-type=log \
>     --log-opt elasticsearch-timeout=10 \
>     --log-opt elasticsearch-version=5 \
>     --log-opt elasticsearch-fields=containerID,containerName,containerImageID,containerImageName,containerLabels,containerEnv \
>         alpine echo this is a test logging message
docker: Error response from daemon: failed to initialize logging driver: error creating logger: error: elasticsearch-options: "elasticsearch: endpoint accepts only http at the moment": elasticsearch: endpoint accepts only http at the moment.
```

**Comment by rchicoli** [comment]
I have this on my todo list, I will try to implement it tonight.

**Comment by rchicoli** [comment]
@megastef I have something working already for elasticsearch v5 : https://travis-ci.org/rchicoli/docker-log-elasticsearch/jobs/345016331
Tomorrow I will try to finish the rest. This is the PR https://github.com/rchicoli/docker-log-elasticsearch/pull/29

**Comment by rchicoli** [comment]
So far it is only supporting version 5 and 6 (https://travis-ci.org/rchicoli/docker-log-elasticsearch/builds/345387892?utm_source=github_status&utm_medium=notification), but it is not merged to master yet, because I still need to implement the changes for elasticsearch version 1 and 2.
Though I might not have much time over this weekend, so I'll get the PR done next week.

**Comment by rchicoli** [comment]
@megastef it is been released a new version, which supports https now. The docker tag is `0.2.1` and you can specify `elasticsearch-username` and `elasticsearch-password`, if necessary.
