### ISSUE TITLE
Expose configuration for elastic client option elastic.SetSniff(false)

### ISSUE THREAD

**Issue by megastef** [rchicoli/docker-log-elasticsearch#28]
Please use the following questions as a guideline for an easier understanding of the issue without further inquiry. Thank you.

### Docker version
17.12
### Elasticsearch version
5 / Sematext Cloud
### Operation System architecture
Max OS X
### Expected behavior
Connect to Elasticsearch for bulk indexing
### Actual behavior
Exit with error "
### Steps to reproduce the behavior
Set  `elasticsearch-url: http://logsene-receiver.sematext.com`

```
docker: Error response from daemon: failed to initialize logging driver: error creating logger: elasticsearch: cannot create a client: elasticsearch: cannot connect to the endpoint: http://logsene-receiver.sematext.com:80
sniff timeout: no Elasticsearch node available.
Stefans-MBP-3:~ stefan$ curl http://logsene-receiver.sematext.com:80/_nodes/http?pretty
{"error":"Request not authorized","errorId":"1590317784350","status":"400"}
```
SaaS services might not expose  _nodes API (same case for AWS Elastic) for security reasons and use typically a load balancer in front of Elasticsearch. 

Solution: 
Initialize client with elastic.SetSniff(false), see https://github.com/olivere/elastic/issues/387

**Comment by rchicoli** [comment]
cool, good to know, I will add an elasticsearch option for enable/disable the sniff. Thank you.

**Comment by rchicoli** [comment]
@megastef thanks for helping again. This issue should be fixed with this PR https://github.com/rchicoli/docker-log-elasticsearch/pull/29 (https://github.com/rchicoli/docker-log-elasticsearch/pull/29/commits/410f72ace9040fce2c6a3127507d2760c6fba6a2).
Well, I guess I should have created a separated PR for this. Anyways, hopefully I can finish it tomorrow.

**Comment by rchicoli** [comment]
@megastef the related PR is merged to master. You can use `elasticsearch-sniff=false` for disabling this feature. In the future versions I could build a retry, if sniff fails to connect, then try without it, something like that.
Could you please try again and let me know if the problem persists? I haven't created an acceptance criteria yet for this feature.
